services:
  node-server:
    build:
      context: .
    image: "maainul/nodejs-docker:latest"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
